require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CreditsController do

  # This should return the minimal set of attributes required to create a valid
  # Credit. As you add validations to Credit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyName", "description" => "MyDescription" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CreditsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all credits as @credits" do
      credit = Credit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:credits).should eq([credit])
    end
  end

  describe "GET show" do
    it "assigns the requested credit as @credit" do
      credit = Credit.create! valid_attributes
      get :show, {:id => credit.to_param}, valid_session
      assigns(:credit).should eq(credit)
    end
  end

  describe "GET new" do
    it "assigns a new credit as @credit" do
      get :new, {}, valid_session
      assigns(:credit).should be_a_new(Credit)
    end
  end

  describe "GET edit" do
    it "assigns the requested credit as @credit" do
      credit = Credit.create! valid_attributes
      get :edit, {:id => credit.to_param}, valid_session
      assigns(:credit).should eq(credit)
    end
  end

  describe "POST create" do

    describe "with valid params" do

      it "creates a new Credit" do
        expect {
          post :create, {:credit => valid_attributes}, valid_session
        }.to change(Credit, :count).by(1)
      end

      it "assigns a newly created credit as @credit" do
        post :create, {:credit => valid_attributes}, valid_session
        assigns(:credit).should be_a(Credit)
        assigns(:credit).should be_persisted
      end

      it "redirects to the list of credits" do
        post :create, {:credit => valid_attributes}, { :return_to => credits_url }
        response.should redirect_to(credits_url)
      end

    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved credit as @credit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Credit.any_instance.stub(:save).and_return(false)
        post :create, {:credit => { "name" => "invalid value" }}, valid_session
        assigns(:credit).should be_a_new(Credit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Credit.any_instance.stub(:save).and_return(false)
        post :create, {:credit => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end

  end

  describe "PUT update" do
    describe "with valid params" do
      let(:person) { FactoryGirl.create(:person) }
      before { sign_in person, no_capybara: true }

      it "updates the requested credit" do
        credit = Credit.create! valid_attributes
        # Assuming there are no other credits in the database, this
        # specifies that the Credit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Credit.any_instance.should_receive(:update).with({ "name" => "MyText" })
        put :update, {:id => credit.to_param, :credit => { "name" => "MyText" }}, valid_session
      end

      it "assigns the requested credit as @credit" do
        credit = Credit.create! valid_attributes
        put :update, {:id => credit.to_param, :credit => valid_attributes}, valid_session
        assigns(:credit).should eq(credit)
      end

      it "redirects to the list of credits" do
        credit = Credit.create! valid_attributes
        put :update, {:id => credit.to_param, :credit => valid_attributes}, { :return_to => credits_url }
        response.should redirect_to(credits_url)
      end

    end

    describe "with invalid params" do
      it "assigns the credit as @credit" do
        credit = Credit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Credit.any_instance.stub(:save).and_return(false)
        put :update, {:id => credit.to_param, :credit => { "name" => "invalid value" }}, valid_session
        assigns(:credit).should eq(credit)
      end

      it "re-renders the 'edit' template" do
        credit = Credit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Credit.any_instance.stub(:save).and_return(false)
        put :update, {:id => credit.to_param, :credit => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested credit" do
      credit = Credit.create! valid_attributes
      expect {
        delete :destroy, {:id => credit.to_param}, valid_session
      }.to change(Credit, :count).by(-1)
    end

    it "redirects to the credits list" do
      credit = Credit.create! valid_attributes
      delete :destroy, {:id => credit.to_param}, valid_session
      response.should redirect_to(credits_url)
    end
  end

end

