require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SocialsController do

  # This should return the minimal set of attributes required to create a valid
  # Social. As you add validations to Social, be sure to
  # adjust the attributes here as well.
  let(:person) { FactoryGirl.create(:person) }
  let(:talk) { FactoryGirl.create(:talk) }
  let(:valid_attributes) { { "talk_id" => talk.id, "person_id" => person.id, "social_type" => "talkinvite", "social_text" => "it begins" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SocialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all socials as @socials" do
      social = Social.create! valid_attributes
      get :index, {}, valid_session
      assigns(:socials).should eq([social])
    end
  end

  describe "GET show" do
    it "assigns the requested social as @social" do
      social = Social.create! valid_attributes
      get :show, {:id => social.to_param}, valid_session
      assigns(:social).should eq(social)
    end
  end

  describe "GET new" do
    it "assigns a new social as @social" do
      get :new, {}, valid_session
      assigns(:social).should be_a_new(Social)
    end
  end

  describe "GET edit" do
    it "assigns the requested social as @social" do
      social = Social.create! valid_attributes
      get :edit, {:id => social.to_param}, valid_session
      assigns(:social).should eq(social)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Social" do
        expect {
          post :create, {:social => valid_attributes}, valid_session
        }.to change(Social, :count).by(1)
      end

      it "assigns a newly created social as @social" do
        post :create, {:social => valid_attributes}, valid_session
        assigns(:social).should be_a(Social)
        assigns(:social).should be_persisted
      end

      it "redirects to the created social" do
        post :create, {:social => valid_attributes}, valid_session
        response.should redirect_to(Social.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved social as @social" do
        # Trigger the behavior that occurs when invalid params are submitted
        Social.any_instance.stub(:save).and_return(false)
        post :create, {:social => { "person_id" => "invalid value" }}, valid_session
        assigns(:social).should be_a_new(Social)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Social.any_instance.stub(:save).and_return(false)
        post :create, {:social => { "person_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested social" do
        social = Social.create! valid_attributes
        # Assuming there are no other socials in the database, this
        # specifies that the Social created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Social.any_instance.should_receive(:update).with({ "person_id" => "1" })
        put :update, {:id => social.to_param, :social => { "person_id" => "1" }}, valid_session
      end

      it "assigns the requested social as @social" do
        social = Social.create! valid_attributes
        put :update, {:id => social.to_param, :social => valid_attributes}, valid_session
        assigns(:social).should eq(social)
      end

      it "redirects to the social" do
        social = Social.create! valid_attributes
        put :update, {:id => social.to_param, :social => valid_attributes}, valid_session
        response.should redirect_to(social)
      end
    end

    describe "with invalid params" do
      it "assigns the social as @social" do
        social = Social.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Social.any_instance.stub(:save).and_return(false)
        put :update, {:id => social.to_param, :social => { "person_id" => "invalid value" }}, valid_session
        assigns(:social).should eq(social)
      end

      it "re-renders the 'edit' template" do
        social = Social.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Social.any_instance.stub(:save).and_return(false)
        put :update, {:id => social.to_param, :social => { "person_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested social" do
      social = Social.create! valid_attributes
      expect {
        delete :destroy, {:id => social.to_param}, valid_session
      }.to change(Social, :count).by(-1)
    end

    it "redirects to the socials list" do
      social = Social.create! valid_attributes
      delete :destroy, {:id => social.to_param}, valid_session
      response.should redirect_to(socials_url)
    end
  end

end
