require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#

describe TalksController do

  # This should return the minimal set of attributes required to create a valid
  # Talk. As you add validations to Talk, be sure to
  # adjust the attributes here as well.

  let(:person) { FactoryGirl.create(:person) }
  let(:valid_attributes) { { "summary" => "MySummary", "person_id" => person.id  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TalksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  ## inspiring talk controller tests go here

end
